# Generated by Django 6.0 on 2025-12-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupUser',
        ),
    ]
